import { type AdminField, type AdminResourceMeta, formatMoney, type Site } from '@charva/contracts';

import { type Row } from '../api/queries';
import { copy, FIELD_LABELS, labelFor } from '../i18n/copy';

/**
 * How a row looks to a person, and where each column belongs on a form.
 *
 * One module rather than twenty screens, for the same reason the CRUD frame is one screen: the
 * columns come from the database and a hand-written layout per table drifts from the schema the
 * moment a migration lands. What is written here is the small amount the schema cannot say —
 * which column is a photograph, which is a pointer to another table, which belongs beside the
 * publish switch rather than beside the title.
 *
 * Everything else is derived. A new column appears in the right group by its kind and its name,
 * and a new table needs nothing at all.
 */

/** Columns that describe *whether and where* a row appears, rather than what it says. */
const PUBLICATION = new Set([
  'isPublished',
  'isFeatured',
  'isCurrent',
  'isPlaceholder',
  'sortOrder',
  'publishedAt',
  'status',
]);

/**
 * A pointer to another row, and the table it points into.
 *
 * The form used to render these as a number box: to attach a day to a tour you had to know that
 * the tour was number seven. The name of the column is not enough to find the table — `tourId`
 * happens to match `tours`, but `stepId` does not match `builder_steps` — so the pairs are
 * written down.
 */
export const FOREIGN_KEYS: Record<string, string> = {
  tourId: 'tours',
  hotelId: 'hotels',
  amenityId: 'amenities',
  stepId: 'builder_steps',
  roomTypeId: 'room_types',
  groupId: 'umrah_groups',
  tripId: 'umrah_trips',
};

/** Which resource a table hangs off, for the sidebar. Editing stays where it is. */
export const PARENT_OF: Record<string, string> = {
  tour_days: 'tours',
  tour_media: 'tours',
  hotel_rooms: 'hotels',
  hotel_media: 'hotels',
  builder_options: 'builder_steps',
  umrah_program_days: 'umrah_trips',
  umrah_group_media: 'umrah_groups',
  hotel_amenities: 'hotels',
};

/**
 * A column holding a `media.id`. Rendered as the photograph, chosen from the library.
 *
 * Matched without regard to case, and that is the whole point: the first version tested
 * `endsWith('MediaId')`, which is true of `coverMediaId`, `posterMediaId` and `avatarMediaId`
 * and **false of `mediaId`** — the plainest and most common of the four. So the galleries, the
 * tour photographs and the group media all kept the number box the picker was written to
 * replace, while the covers beside them did not, which is the kind of half-working that is
 * harder to notice than nothing working at all.
 */
export function isMediaField(field: AdminField): boolean {
  return field.kind === 'int' && field.name.toLowerCase().endsWith('mediaid');
}

export function isForeignKey(field: AdminField): boolean {
  return FOREIGN_KEYS[field.name] !== undefined;
}

/**
 * Short text columns with a settled vocabulary, offered as a list of what is already in use.
 *
 * `gallery_items.category` is a `VARCHAR` holding `nature`, `cities`, `history`, `culture`,
 * `food` — a set in practice and free text in the schema, so the form asked an editor to
 * remember which of five words it was and to spell it the way the last person did. Suggesting
 * the values already in the table costs one request and removes the whole class of «Nature»
 * beside «nature», while still allowing a sixth.
 */
const SUGGESTED = new Set(['category', 'city', 'region', 'tag', 'blockCode', 'unit', 'icon']);

export function hasSuggestions(field: AdminField): boolean {
  return (field.kind === 'string' || field.kind === 'enum') && SUGGESTED.has(field.name);
}

export interface FieldGroups {
  /** What the row says: its names, its text. The bulk of the form. */
  main: AdminField[];
  /** Numbers, dates, enumerations — the facts about it. */
  facts: AdminField[];
  /** Photographs and videos. */
  media: AdminField[];
  /** Which row of another table this belongs to. */
  links: AdminField[];
  /** Whether it is visible, where it sits, what state it is in. */
  publication: AdminField[];
  /** Generated by the database: id, created_at. Shown, but out of the way. */
  system: AdminField[];
}

export function groupFields(fields: readonly AdminField[]): FieldGroups {
  const groups: FieldGroups = {
    main: [],
    facts: [],
    media: [],
    links: [],
    publication: [],
    system: [],
  };

  for (const field of fields) {
    if (field.readOnly) groups.system.push(field);
    else if (isMediaField(field)) groups.media.push(field);
    else if (isForeignKey(field)) groups.links.push(field);
    else if (PUBLICATION.has(field.name)) groups.publication.push(field);
    else if (field.kind === 'localized' || field.kind === 'string' || field.kind === 'text') {
      groups.main.push(field);
    } else groups.facts.push(field);
  }

  return groups;
}

export interface Presented {
  /** What to call this row. Never «#7» unless the table genuinely has no name. */
  title: string;
  /** Two or three facts from its own columns — «3 дня · от 540 $ · Пустыня». */
  facts: string[];
  /** The row's photograph, when it has one. */
  mediaId: number | null;
  badges: { label: string; tone: 'draft' | 'state' | 'flag' }[];
}

/**
 * A row, as a card.
 *
 * The list used to print the primary key and one title, which for `tour_days` reads «День: 3»
 * beside twenty other rows reading «День: 3» — true, and useless. What identifies a row to the
 * person looking for it is its name, then the two or three facts that distinguish it from its
 * neighbours, then whether it is live.
 */
export function presentRow(row: Row, resource: AdminResourceMeta): Presented {
  return {
    title: titleOf(row, resource),
    facts: factsOf(row, resource),
    mediaId: mediaIdOf(row, resource),
    badges: badgesOf(row),
  };
}

/**
 * Something to click, whatever the table is.
 *
 * Tried in the order a human would: the translated title, then a name, then a slug or a code,
 * then the primary key. A row that shows only «#41» is still openable, which is the point —
 * some of these tables genuinely have no human-facing name.
 */
export function titleOf(row: Row, resource: AdminResourceMeta): string {
  for (const field of resource.fields) {
    const value = row[field.name];

    if (field.kind === 'localized' && value !== null && typeof value === 'object') {
      const first = Object.values(value as Record<string, string>).find(
        (text) => typeof text === 'string' && text.trim() !== '',
      );
      if (first !== undefined) return first;
    }
  }

  for (const key of [
    'slug',
    'code',
    'keyName',
    'settingKey',
    'blockCode',
    'slotKey',
    'authorName',
  ]) {
    const value = row[key];
    if (typeof value === 'string' && value !== '') return value;
  }

  for (const key of ['departAt', 'dayNumber', 'createdAt']) {
    const value = row[key];
    if (value !== null && value !== undefined) {
      return `${labelFor(FIELD_LABELS, key)}: ${plain(value, key, resource.site)}`;
    }
  }

  return `#${String(row['id'])}`;
}

/** At most three, because a fourth is read by nobody and pushes the title off the line. */
function factsOf(row: Row, resource: AdminResourceMeta): string[] {
  const facts: string[] = [];

  for (const field of resource.fields) {
    if (facts.length === 3) break;
    if (field.readOnly || PUBLICATION.has(field.name) || isMediaField(field)) continue;
    if (isForeignKey(field) || field.kind === 'localized' || field.kind === 'json') continue;
    if (field.name === 'slug' || field.name === 'id') continue;

    const value = row[field.name];
    if (value === null || value === undefined || value === '') continue;
    if (field.kind === 'boolean') continue;

    const text = plain(value, field.name, resource.site);
    if (text === '') continue;

    // The number alone for a quantity, the label with it otherwise: «3 дня» reads, «Категория:
    // Пустыня» reads, «Дней: 3» in a row of five such pairs does not.
    facts.push(field.kind === 'enum' ? text : `${labelFor(FIELD_LABELS, field.name)}: ${text}`);
  }

  return facts;
}

function mediaIdOf(row: Row, resource: AdminResourceMeta): number | null {
  for (const field of resource.fields) {
    if (!isMediaField(field)) continue;
    const value = row[field.name];
    if (typeof value === 'number') return value;
  }
  return null;
}

function badgesOf(row: Row): Presented['badges'] {
  const badges: Presented['badges'] = [];

  if (row['isPublished'] === false) badges.push({ label: copy.list.draft, tone: 'draft' });
  if (typeof row['status'] === 'string') {
    badges.push({ label: copy.statuses[row['status']] ?? row['status'], tone: 'state' });
  }
  if (row['isCurrent'] === true)
    badges.push({ label: labelFor(FIELD_LABELS, 'isCurrent'), tone: 'flag' });
  if (row['isFeatured'] === true)
    badges.push({ label: labelFor(FIELD_LABELS, 'isFeatured'), tone: 'flag' });
  if (row['isPlaceholder'] === true) badges.push({ label: copy.list.temporary, tone: 'draft' });

  return badges;
}

/**
 * One value as one short string.
 *
 * Money knows its currency from the site — dollars on Global, manat on Umrah (decision D-24) —
 * and a date is a date rather than an ISO instant with a `T` in the middle of it.
 */
export function plain(value: unknown, name: string, site: Site | null): string {
  if (value === null || value === undefined) return '';

  if (typeof value === 'number' && name.endsWith('Minor')) {
    return formatMoney({ minor: value, currency: site === 'umrah' ? 'TMT' : 'USD' });
  }

  if (typeof value === 'string' && /^\d{4}-\d{2}-\d{2}/.test(value)) {
    const [date, time] = value.split('T');
    const parts = (date ?? '').split('-');
    const stamp = `${parts[2] ?? ''}.${parts[1] ?? ''}.${parts[0] ?? ''}`;
    return time === undefined ? stamp : `${stamp}, ${time.slice(0, 5)}`;
  }

  if (typeof value === 'string') return value;
  if (typeof value === 'number') return String(value);
  if (typeof value === 'boolean') return value ? 'да' : 'нет';

  // A JSON column, an array, anything else: this function returns one short line, and there is
  // no short line for a bag of keys. The caller drops the empty string rather than printing
  // «[object Object]» in a list of facts.
  return '';
}

/**
 * Where this row can be seen by a visitor, or `null` when it has no page of its own.
 *
 * «Не видно результата» was the complaint: an editor saved a tour and had no way to look at
 * what they had done. The origins come from the environment so the link works in development
 * against `localhost` and in production against the real subdomains.
 */
const env = import.meta.env as Record<string, string | undefined>;

const ORIGINS: Record<'global' | 'umrah', string> = {
  global: env['VITE_GLOBAL_ORIGIN'] ?? 'http://localhost:5181',
  umrah: env['VITE_UMRAH_ORIGIN'] ?? 'http://localhost:5182',
};

const PUBLIC_PATHS: Record<string, { site: 'global' | 'umrah'; path: (slug: string) => string }> = {
  tours: { site: 'global', path: (slug) => `/ru/tours/${slug}` },
  hotels: { site: 'global', path: (slug) => `/ru/hotels/${slug}` },
  articles: { site: 'global', path: (slug) => `/ru/articles/${slug}` },
  ziyarat_places: { site: 'umrah', path: (slug) => `/tm/ziyarat/${slug}` },
  umrah_groups: { site: 'umrah', path: () => `/tm/suratlar` },
};

export function publicUrl(resource: string, row: Row): string | null {
  const target = PUBLIC_PATHS[resource];
  if (target === undefined) return null;

  const slug = row['slug'];
  if (typeof slug !== 'string' || slug === '') return null;

  return `${ORIGINS[target.site]}${target.path(slug)}`;
}
